#!/bin/bash
#
# $Id$

. Config-funcs

echo Configuring release version

export CXXFLAGS="-O3" 
export LDFLAGS="" 
export CPPFLAGS=""

findlibs $@ || return 1

cd bin-release
../configure --prefix=$PWD $@
