#!/bin/bash
#
# $Id$

. Config-funcs

echo Configuring release version

export CXXFLAGS="-O3" 
export LDFLAGS=""
export CPPFLAGS="-std=gnu++11"

findlibs $@ || exit 1

cd bin-release
../configure --prefix=$PWD $@
