#!/bin/bash
#
# New and hopefully very much easier configuration script
#

# ============================================================

AddAM() {
  while read path; do
    if [ "$path" ]; then
      echo "configure: $path.am"
    fi
  done
}

# ============================================================

contains()
{
  key=$1
  shift
  for a; do
    if [ $a == $key ]; then return 0;
    fi
  done
  return 1
}

# ============================================================

try_gmp() {
  if [ -f $1/gmp.h ]; then
    for gmplib in libgmp.a libgmp.so libgmp.dll.a; do
      if [ -f $2/$gmplib ]; then
        printf "GMP Library found\n"
        printf "    gmp.h found at $1\n"
        printf "    %s found at $2\n" "$gmplib"

        CPPFLAGS="-I$1 $CPPFLAGS"
        LDFLAGS="-L$2 $LDFLAGS"
        return 0
      fi
    done
  fi
  return 1
}

find_gmp() {
  try_gmp $GMP_INCLUDE $GMP_LIBRARY && return 0
  try_gmp /opt/local/include /opt/local/lib && return 0
  try_gmp /usr/local/include /usr/local/lib && return 0
  try_gmp /usr/local/include /usr/local/lib64 && return 0
  try_gmp /usr/include /usr/lib && return 0
  try_gmp /usr/include /usr/lib64 && return 0
  try_gmp /usr/include/x86_64-linux-gnu /usr/lib/x86_64-linux-gnu && return 0
  try_gmp /mingw/include /mingw/lib && return 0
  printf "Could not find gmp Library, switching to --without-gmp.\n"
  printf "You can specify the location using environment variables\n"
  printf "GMP_INCLUDE (the path to gmp.h) and GMP_LIBRARY.\n\n"
  return 1
}

# ============================================================


printf "\n------------------------------------------------------------\n"
printf "Building configure script"
printf "\n------------------------------------------------------------\n"
printf "\n"

tmpmf=`mktemp`
printf "configure: configure.ac\n\tautoreconf --force --install\n\n" > $tmpmf

awk '/AC_CONFIG_FILES/{p=1} {if (p) print} /\]\)/{p=0}' configure.ac | sed 's/AC_CONFIG_FILES(\[//' | tr -d ')]' | AddAM >> $tmpmf

make -f $tmpmf
if [ "$?" -ne "0" ]; then 
  printf "\nCouldn't build configure script, bailing out.\n\n"
  rm $tmpmf
  exit 1
fi
rm $tmpmf


printf "\n------------------------------------------------------------\n"
printf "Checking for libraries"
printf "\n------------------------------------------------------------\n"
printf "\n"

export CC=gcc
export CXX=g++
export CXXFLAGS="$CXXFLAGS -Wall -std=c++11 -DNDEBUG"
export CPPFLAGS=""
export LDFLAGS="$LDFLAGS -static -static-libgcc -static-libstdc++"

GMP_STATUS=""

if contains "--without-gmp" $@; then
  echo "Building without GMP library"
  GMP_STATUS="--without-gmp"
else
  find_gmp || GMP_STATUS="--without-gmp"
fi


printf "\n"
printf "\n------------------------------------------------------------\n"
printf "Configuring development version"
printf "\n------------------------------------------------------------\n"
printf "\n"

if [ ! -d bin-devel ]; then
  mkdir bin-devel
fi
cd bin-devel

COMMON_CXXFLAGS="$CXXFLAGS"
CXXFLAGS="-ggdb -DDEVELOPMENT_CODE $COMMON_CXXFLAGS"
../configure --prefix=$PWD $@ $GMP_STATUS 
ok="$?"
cd ..

if [ "$ok" != "0" ]; then
  exit 1
fi

printf "\n"
printf "\n------------------------------------------------------------\n"
printf "Configuring release version"
printf "\n------------------------------------------------------------\n"
printf "\n"

if [ ! -d bin-release ]; then
  mkdir bin-release
fi
cd bin-release

CXXFLAGS="-O3 $COMMON_CXXFLAGS"
../configure --prefix=$PWD $@ $GMP_STATUS 
ok="$?"
cd ..

if [ "$ok" != "0" ]; then
  exit 1
fi

printf "\n"
printf "\n------------------------------------------------------------\n"
printf "Summary"
printf "\n------------------------------------------------------------\n"
printf "\n"

if [ "$GMP_STATUS" ]; then
  echo "GMP library: NOT FOUND.  Some features will be missing!"
else
  echo "GMP library: found"
fi


printf "\n"
