#!/bin/bash
#

. Config-funcs

echo Configuring development version

export CXXFLAGS="-ggdb -DDEVELOPMENT_CODE" 
export LDFLAGS="" 
export CPPFLAGS="-std=gnu++11"

findlibs $@ || exit 1

if [ ! -d bin-devel ]; then
  mkdir bin-devel
fi
cd bin-devel
../configure --prefix=$PWD $@
