#!/bin/bash
#
# New and hopefully very much easier configuration script
#

# ============================================================

AddAM() {
  while read path; do
    if [ "$path" ]; then
      echo "configure: $path.am"
    fi
  done
}

# ============================================================

contains()
{
  key=$1
  shift
  for a; do
    if [ $a == $key ]; then return 0;
    fi
  done
  return 1
}

# ============================================================

try_gmp() {
  if [ -f $1/gmp.h ]; then
    for gmplib in libgmp.a libgmp.so libgmp.dll.a; do
      if [ -f $2/$gmplib ]; then
        printf "GMP Library found\n"
        printf "    gmp.h found at $1\n"
        printf "    %s found at $2\n" "$gmplib"

        CPPFLAGS="-I$1 $CPPFLAGS"
        LDFLAGS="-L$2 $LDFLAGS"
        return 0
      fi
    done
  fi
  return 1
}

find_gmp() {
  try_gmp $GMP_INCLUDE $GMP_LIBRARY && return 0
  try_gmp /opt/local/include /opt/local/lib && return 0
  try_gmp /usr/local/include /usr/local/lib && return 0
  try_gmp /usr/local/include /usr/local/lib64 && return 0
  try_gmp /usr/include /usr/lib && return 0
  try_gmp /usr/include /usr/lib64 && return 0
  try_gmp /usr/include/x86_64-linux-gnu /usr/lib/x86_64-linux-gnu && return 0
  try_gmp /mingw/include /mingw/lib && return 0
  printf "Could not find gmp Library, switching to --without-gmp.\n"
  printf "You can specify the location using environment variables\n"
  printf "GMP_INCLUDE (the path to gmp.h) and GMP_LIBRARY.\n\n"
  return 1
}

# ============================================================

try_mddlib() {
  if [ -f $1/meddly.h ]; then
     if [ -f $2/libmeddly.a ]; then
        printf "MDD Library found\n"
        printf "    meddly.h found at $1\n"
        printf "    libmeddly.a found at $2\n"
        CPPFLAGS="-I$1 $CPPFLAGS"
        LDFLAGS="-L$2 $LDFLAGS"
        export MDD_LIBRARY="$2"
        return 0
    fi
  fi
  return 1
}

find_mddlib() {
  try_mddlib $MDD_INCLUDE $MDD_LIBRARY && return 0
  try_mddlib $HOME/meddly/trunk/include $HOME/meddly/trunk/lib && return 0
  try_mddlib $HOME/Meddly/trunk/include $HOME/Meddly/trunk/lib && return 0
  try_mddlib $HOME/meddly/include $HOME/meddly/lib && return 0
  try_mddlib $HOME/Meddly/include $HOME/Meddly/lib && return 0
  printf "Cannot find MDD Library, switching to --without-meddly.\n"
  printf "You can specify the location using environment variables\n"
  printf "MDD_INCLUDE (the path to meddly.h) and MDD_LIBRARY\n"
  return 1
}

# ============================================================


printf "\n------------------------------------------------------------\n"
printf "Building configure script"
printf "\n------------------------------------------------------------\n"
printf "\n"

tmpmf=`mktemp`
printf "configure: configure.ac\n\tautoreconf --force --install\n\n" > $tmpmf

awk '/AC_CONFIG_FILES/{p=1} {if (p) print} /\]\)/{p=0}' configure.ac | sed 's/AC_CONFIG_FILES(\[//' | tr -d ')]' | AddAM >> $tmpmf

make -f $tmpmf
if [ "$?" -ne "0" ]; then 
  printf "\nCouldn't build configure script, bailing out.\n\n"
  rm $tmpmf
  exit 1
fi
rm $tmpmf


printf "\n------------------------------------------------------------\n"
printf "Checking for libraries"
printf "\n------------------------------------------------------------\n"
printf "\n"

export CC=g++
export CXX=g++
export CXXFLAGS="$CXXFLAGS -Wall"
export LDFLAGS="" 
export CPPFLAGS="-std=gnu++11"


GMP_STATUS=""
MEDDLY_STATUS=""

if contains "--without-gmp" $@; then
  echo "Building without GMP library"
  GMP_STATUS="--without-gmp"
else
  find_gmp || GMP_STATUS="--without-gmp"
fi

if contains "--without-meddly" $@; then
  echo "Building without MEDDLY"
  MEDDLY_STATUS="--without-meddly"
else
  find_mddlib || MEDDLY_STATUS="--without-meddly"
fi

printf "\n"
printf "\n------------------------------------------------------------\n"
printf "Configuring development version"
printf "\n------------------------------------------------------------\n"
printf "\n"

if [ ! -d bin-devel ]; then
  mkdir bin-devel
fi
cd bin-devel

COMMON_CXXFLAGS="$CXXFLAGS"
CXXFLAGS="-ggdb -DDEVELOPMENT_CODE $COMMON_CXXFLAGS"
../configure --prefix=$PWD $@ $GMP_STATUS $MEDDLY_STATUS
ok="$?"
cd ..

if [ "$ok" != "0" ]; then
  exit 1
fi

printf "\n"
printf "\n------------------------------------------------------------\n"
printf "Configuring release version"
printf "\n------------------------------------------------------------\n"
printf "\n"

if [ ! -d bin-release ]; then
  mkdir bin-release
fi
cd bin-release
CXXFLAGS="-O3 $COMMON_CXXFLAGS"
../configure --prefix=$PWD $@ $GMP_STATUS $MEDDLY_STATUS
ok="$?"
cd ..

if [ "$ok" != "0" ]; then
  exit 1
fi

printf "\n"
printf "\n------------------------------------------------------------\n"
printf "Summary"
printf "\n------------------------------------------------------------\n"
printf "\n"

if [ "$GMP_STATUS" ]; then
  echo "GMP library: NOT FOUND.  Some features will be missing!"
else
  echo "GMP library: found"
fi

if [ "$MEDDLY_STATUS" ]; then
  printf "MEDDLY: NOT FOUND.  Some features will be missing!\n"
else
  printf "MEDDLY: found"
#
# See if we can determine if MEDDLY was built --without-gmp
#
  if [ -f $MDD_LIBRARY/../config.h ]; then
    if grep -q "#define HAVE_LIBGMP" $MDD_LIBRARY/../config.h; then
      printf ", built with GMP support\n"
    else
      printf ", built without GMP support.\n"
      if [ ! "$GMP_STATUS" ]; then
        printf "\tTHIS COULD CAUSE LINKER ERRORS.\n"
      fi
    fi
  else
    printf "\n"
  fi
fi

printf "\n"
