#!/bin/bash
#
# $Id$

. Config-funcs

echo Configuring development version

export CXXFLAGS="-ggdb -DDEVELOPMENT_CODE" 
export LDFLAGS="" 
export CPPFLAGS="-std=gnu++11"

findlibs $@ || exit 1

cd bin-devel
../configure --prefix=$PWD $@
