#!/bin/csh

#
# $Id$
#
# This script is used to build a platform-dependent makefile
#

echo Building makefile for platform $SMART_PLATFORM
cd ../$SMART_PLATFORM
touch ../Source/smart.tab.h
cat make.platform ../Source/make.common >! makefile
echo Generating dependencies
make depend
cat make.platform ../Source/make.common make.depend >! makefile
rm ../Source/smart.tab.h
endif
