#!/bin/csh

#
# $Id$
#
# Builds the appropriate development version of SMART
#

if ( $HOSTTYPE == "i386-linux" ) then 
  echo Running make for devel-i386-linux
  cd ../devel-i386-linux
  make makefile 
  make $1 $2 $3 $4 $5
else if ( $HOSTTYPE == "i386-solaris" ) then
  echo Running make for devel-i386-solaris
  cd ../devel-i386-solaris
  make makefile
  make $1 $2 $3 $4 $5
else if ( $HOSTTYPE == "macintosh" ) then
  echo Running make for devel-macintosh
  cd ../devel-macintosh
  make makefile
  make $1 $2 $3 $4 $5
else 
  echo Running generic make
  cd ../generic
  make makefile
  make $1 $2 $3 $4 $5
endif
	
echo "Done"    


