#!/bin/csh

#
# $Id$
#
# Builds the appropriate development version of SMART
# based on the environment variable SMART_PLATFORM
#

echo Running make for platform: $SMART_PLATFORM
cd ../$SMART_PLATFORM
make makefile 
make $1 $2 $3 $4 $5

echo "Done"    


