#!/bin/tcsh

#
# $Id$ 
#
# Usage: Test file1 ... filen
#
# Tests programs using "TestOne". 
#

set ok = `env | grep "SMART_PLATFORM" | wc -c`
if ( $ok ) then
  echo Running Test for platform: $SMART_PLATFORM
else
  echo Please set environment variable SMART_PLATFORM
  exit
endif

#Use color for linux boxes
set linux = `env | grep "SMART_PLATFORM" | grep "linux" | wc -c`

set calldir = $cwd
set j = 1
set stop = $#
while ($j <= $stop) 
  set file = $argv[$j]
  @ j++
# if there is no output file, don't bother trying to test
  cd $file:h
  set base = $file:t
  if (-e $base.out) then
    $calldir/TestOne $file:t $linux
  endif
cd $calldir
end 

