
// $Id$

#ifndef SETS_H
#define SETS_H

/** @name sets.h
    @type File
    @args \ 

  Results for sets.
  Basic set expressions.
  Set operators.

  Right now, only integer and real sets are supported.
 
 */

#include "exprs.h"

//@{
  



// ******************************************************************
// *                                                                *
// *                        set_result class                        *
// *                                                                *
// ******************************************************************

/**   The base class for sets, as generated by a set expression.
      Also used within arrays to define the index values.
      Note: like expressions, we count the number of incoming
      pointers.  That's so we can share the same set
      (for instance, within multiple arrays).
*/  

class set_result {
  /// The number of incoming pointers
  int incoming;
  /// Number of elements
  int size;  
public:
  set_result(int s);
  virtual ~set_result();

  inline int Size() const { return size; }

  /** Get the nth item of the set.
      n must be between 0 and Size()-1.
   */
  virtual void GetElement(int n, result &x) = 0;

  /** The position of x in the set.
      If x is not contained in the set, we return -1.
      Note that this is the inverse of GetElement.
   */
  virtual int IndexOf(const result &x) = 0;

  /** Get the index and value of the nth smallest element of the set.
      n must be between 0 and Size()-1.
      This is used during set union, intersection, etc.
   */
  virtual void GetOrder(int n, int &i, result &x) = 0;

  /// For display purposes.
  virtual void show(OutputStream &s) = 0;

  friend set_result* Copy(set_result *e);
  friend void Delete(set_result *e);
};

inline OutputStream& operator<< (OutputStream &s, set_result *r) 
{
  r->show(s);
  return s;
}

/**  Create a "copy" of this set.
     Since we share pointers, this simply
     increases the incoming pointer count.
 */
inline set_result* Copy(set_result *s)
{
  if (s) s->incoming++;
  return s;
}

/**  Delete a set.
     We decrease the incoming pointer count, and if
     it reaches zero, then we delete the set.
 */
inline void Delete(set_result *s)
{
  if (s) {
    DCASSERT(s->incoming>0);
    s->incoming--;
    if (0==s->incoming) delete s;
  }
}


// ******************************************************************
// *                                                                *
// *           Global functions  to build set expressions           *
// *                                                                *
// ******************************************************************

/**  Builds an interval set expression.
     The arguments must be all the same type.
 */
expr*  MakeInterval(const char* fn, int line, expr* start, expr* stop, expr* inc);

/**  Builds a set with a single element.
 */
expr*  MakeElementSet(const char* fn, int line, expr* element);

/**  Builds a set (expression) as the union of other sets.
 */
expr*  MakeUnionOp(const char* fn, int line, expr* left, expr* right);

/**  Converts a set of integers into a set of reals.
 */
expr*  MakeInt2RealSet(const char* fn, int line, expr* intset);

//@}

#endif

