#!/bin/bash
#
# $Id$
#
# Runs test cases
#

OK=" [1;32m   OK   [0;39m"
CHANGE=" [1;33m CHANGE [0;39m"
FAILED=" [1;31m FAILED [0;39m"

for inf in 1 2 3
do
  infile="dbin$inf.txt"
  if [ -f $infile ]; then
    echo $infile
    for ih in "i" "h"
    do
      for rst in "r" "s" "t"
      do
        outfile="dbout$inf.$ih.$rst.txt"
        if [ -f $outfile ]; then
          printf "  %-40s  " $outfile
          if ./dbtest -$ih -$rst < $infile > /tmp/foo.txt 2> /dev/null; then
            # successful run
            if diff /tmp/foo.txt $outfile > /dev/null; then
              echo $OK
            else
              echo $CHANGE
            fi
          else
            echo $FAILED
          fi
        fi
      done
    done
  fi
done

