#!/bin/bash
#
# $Id$
#
# Runs test cases
#

OK=" [1;32m   OK   [0;39m"
CHANGE=" [1;33m CHANGE [0;39m"
FAILED=" [1;31m FAILED [0;39m"

infile=$1
if [ -f $infile ]; then
    echo $infile
    inf=`basename $infile .txt | cut -c 5-10`
    for ih in "i" "h"
    do
      for rst in "r" "s" "t"
      do
        outfile="dbout$inf.$ih.$rst.txt"
        if [ -f $outfile ]; then
          printf "  %-40s  " $outfile
          if ./dbtest -$ih -$rst < $infile > /tmp/foo.txt 2> /dev/null; then
            # successful run
            if diff -b /tmp/foo.txt $outfile > /dev/null; then
              echo $OK
            else
              echo $CHANGE
              exit 1
            fi
          else
            echo $FAILED
            exit 2
          fi
        fi
      done
    done
else
    echo "Didn't find input file $infile"
    exit 1
fi

