remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"

url: "https://asminer.github.io"
baseurl: "/smart"
repository: asminer/smart
title: SMART
title_separator: "|"
description: Stochastic Model-checking Analyzer for Reliability and Timing

plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

collections:
  basics:
    output: true
    permalink: /:collection/:path/
  examples:
    output: true
    permalink: /:collection/:path/

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      sidebar:
        nav: "side"
  # _basics
  - scope:
      path: ""
      type: basics
    values:
      layout: single
      sidebar:
        nav: "side"
  # _examples
  - scope:
      path: ""
      type: examples
    values:
      layout: single
      sidebar:
        nav: "side"
