remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"

url: "https://asminer.github.io"
baseurl: "/smart"
repository: asminer/SMART
title: SMART
description: Stochastic Model-checking Analyzer for Reliability and Timing

plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

