#!/bin/bash

#
# $Id$
#
# Builds the revision number.
#

if [ $# -ne 1 ]; then
  echo Usage: $0 "<repospath>"
  exit
fi

path=$1
revfile=$path/revision.h

rev=`svn info $path | awk '/Revision/{print $2}'`
if [ -z "$rev" ]; then
  if [ -e $revfile ]; then
    printf "Leaving old revision number\n"
  else
    printf "Using bogus revision number\n";
    printf "const int REVISION_NUMBER = 0 ;\n" > $revfile
  fi
else
  if [ -e $revfile ]; then
    revlast=`awk '{print $5}' $revfile`
    if [ "$rev" -eq "$revlast" ]; then
      printf "No revision number change since last build\n";
    else
      printf "Updating revision number to %d\n" $rev
      printf "const int REVISION_NUMBER = $rev ;\n" > $revfile
    fi
  else
    printf "Updating revision number to %d\n" $rev
    printf "const int REVISION_NUMBER = $rev ;\n" > $revfile
  fi
fi

